### ISSUE TITLE
SocketConnection pattern guidance

### ISSUE THREAD

**Issue by Wraith2** [mgravell/Pipelines.Sockets.Unofficial#11]
I'm using SocketConnections to handle all the unpleasantness of buffer reconstruction which requires that write something to handle incoming data in async ways and I wondering whether the implementation I'm arriving at is safe and relatively performant, I'm not particularly well versed in TAP subtleties.

This [basic implementation](https://gist.github.com/Wraith2/f47f94ff51145f730fbf0b398bce997e) needs to wrap a socket and keep receiving data then feeding it into a parser, Valid message output from the parser will be dispatched through an event and the data passed out through that event should hopefully remain alive until the handler returns so that large payloads don't end up being copied about. Could you look and comment on whether this is appropriate/correct/improvable?

**Comment by mgravell** [comment]
Looks broadly fine. I'd probably try to avoid dealing in *lengths* all the time, because in some edge cases this can cause catastrophic performance (usually when dealing with massively recursive models) - if you can deal in *positions* rather than *lengths* it may work better, but: in most cases (the ones not I volving massively recursive models) it won't matter. I can't see the parser code - note that for optimal performance you want to use a ref-counting "buffer reader" that tracks a span, rather than constantly accessing spans from the buffer. SE.Redis and protobuf-net both have examples of this that you may find useful.

**Comment by Wraith2** [comment]
Ok, thanks, that's good. I was worried about the looping with tasks. I'd normally approach this with a dedicated thread and events but that doesn't scale.

The parser implementation contains protocol details which are proprietary so I can't post that unfortunately. The protocol is pretty simple flat utf8 encoded nesting. The parser takes the sequence and attempts to pull apart each slice, I can show [that part](https://gist.github.com/Wraith2/ca88edf37d78e0f8304527d034766a62), I grab each segment span and attempt to consume it as far as possible skipping any known prefix so I avoid re-running a complex parse if possible.

I'm not sure what you mean with the lengths. The Message object returned by the parser will always start at offset 0 so length is both a length and a relative position, Which part would you change and what approach would be better?

I'll find and take a look at the SE.Redis code, that's probably closest to what I'm doing.
