### ISSUE TITLE
StreamConnection.ConnectAsync is not working.

### ISSUE THREAD

**Issue by aensidhe** [mgravell/Pipelines.Sockets.Unofficial#9]
Not that it's blocking something, but :)

I think `args.RemoteEndpoint` should be filled, but no one does it [here](https://github.com/mgravell/Pipelines.Sockets.Unofficial/blob/55062fa9feea7284df39595fd53a61244f914c61/src/Pipelines.Sockets.Unofficial/SocketConnection.Connect.cs#L43)

**Comment by mgravell** [comment]
Yeah, that's a [bad change 23 hours ago](https://github.com/mgravell/Pipelines.Sockets.Unofficial/commit/9dae5654d139ff7240194e23b3538ebf520fe506#diff-9b3f71c7c23be4eca02bb4b5beeacd5dL80); I didn't notice it because in my "real" usage we connect the socket manually. I need to sit down and write sensible tests! Thanks, will fix ASAP

**Comment by mgravell** [comment]
fixed in [0.2.1-alpha.91](https://www.nuget.org/packages/Pipelines.Sockets.Unofficial/0.2.1-alpha.91)
